Vagrant.configure("2") do |config|
  config.vm.box = "minimal/centos7"

  config.vm.define "admin01" do |admin01|
    admin01.vm.hostname="admin01"
    admin01.vm.box_check_update = false
    admin01.vm.box_version = "7.0"
    admin01.vm.network "private_network", type: "dhcp"
    admin01.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "256"
      vb.cpus = 1
    end
  end

  config.vm.define "server01" do |server01|
    server01.vm.hostname="server01"
    server01.vm.box_check_update = false
    server01.vm.box_version = "7.0"
    server01.vm.network "private_network", type: "dhcp"
    server01.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "256"
      vb.cpus = 1
    end
  end

  config.vm.define "server02" do |server02|
    server02.vm.hostname="server02"
    server02.vm.box_check_update = false
    server02.vm.box_version = "7.0"
    server02.vm.network "private_network", type: "dhcp"
    server02.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "256"
      vb.cpus = 1
    end
  end

#  config.vm.provision "shell", inline: <<-SHELL
#     yum update
#   SHELL
end
