Vagrant.configure("2") do |config|

  # Box Setting
  config.vm.box = "minimal/centos7"
  config.vm.hostname = "localuser"
  config.vm.box_check_update = false
  config.vm.box_version = "7.0"
  # Box provider
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false

    # Customize the amount of memory on the VM:
    vb.memory = "256"

    # Customize the amount of cpu on the VM:
    vb.cpus = 1
  end

  config.vm.provision "shell", inline: <<-SHELL
     yum update
   SHELL
end
